"""Tests for scripts/measure_abstention_distributions.py (M1/M2 of
docs/specs/safe-abstention-defaults).

The script lives under scripts/ (not in the package), so we import it
through a path injection. Tests are structural — they pin the report's
shape and the sweep/verdict math on synthetic rows, not the live
corpus numbers (those move with the corpus and live in the committed
measurements.md, regenerated by the script).
"""

from __future__ import annotations

import sys
from pathlib import Path

_SCRIPTS_DIR = Path(__file__).resolve().parent.parent.parent / "scripts"
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

import measure_abstention_distributions as mad  # noqa: E402


def _row(top1: float, per_token: float, gap: float, n_tokens: float = 3.0) -> dict[str, float]:
    return {"top1": top1, "per_token": per_token, "gap": gap, "n_tokens": n_tokens}


class TestQueryStats:
    def test_shapes_and_zero_candidate_queries(self) -> None:
        class OneEntryCorpus:
            name = "one-entry-fake"

            def get(self, path):
                return None

            def entries(self):
                from attune_rag.corpus.base import RetrievalEntry

                return [
                    RetrievalEntry(
                        path="concepts/widget.md",
                        summary="widget frobnication guide",
                        content="how to frobnicate the widget",
                        aliases=[],
                        related=[],
                        category="concepts",
                    )
                ]

        rows = mad.query_stats(
            [{"query": "frobnicate widget"}, {"query": "quantum sourdough"}],
            OneEntryCorpus(),
        )
        assert len(rows) == 2
        hit, miss = rows
        assert hit["top1"] > 0
        assert hit["gap"] == hit["top1"]  # single candidate → gap == top1
        assert miss["top1"] == 0.0
        assert miss["per_token"] == 0.0

    def test_stat_keys(self) -> None:
        assert set(_row(1, 1, 1)) == {"top1", "per_token", "gap", "n_tokens"}


class TestSweep:
    def test_fractions(self) -> None:
        legit = [_row(10, 2.0, 5), _row(4, 1.0, 2)]
        negs = [_row(1, 0.2, 0.5), _row(3, 0.6, 1.0)]
        rows = mad.sweep_heuristic(legit, negs, lambda r, t: r["top1"] >= t, [0.0, 5.0])
        assert rows[0] == {"threshold": 0.0, "legit_kept": 1.0, "negatives_abstained": 0.0}
        assert rows[1] == {"threshold": 5.0, "legit_kept": 0.5, "negatives_abstained": 1.0}


class TestBestBothCorpora:
    def _sweeps(self, help_rows, cb_rows):
        return {"help": help_rows, "corpus_b": cb_rows}

    def test_picks_max_min_abstention_over_eligible(self) -> None:
        help_rows = [
            {"threshold": 0.0, "legit_kept": 1.0, "negatives_abstained": 0.0},
            {"threshold": 1.0, "legit_kept": 1.0, "negatives_abstained": 0.8},
        ]
        cb_rows = [
            {"threshold": 0.0, "legit_kept": 1.0, "negatives_abstained": 0.0},
            {"threshold": 1.0, "legit_kept": 0.96, "negatives_abstained": 0.9},
        ]
        best = mad.best_both_corpora(self._sweeps(help_rows, cb_rows))
        assert best is not None
        assert best["threshold"] == 1.0
        assert best["min_negatives_abstained"] == 0.8

    def test_ineligible_corpus_excludes_threshold(self) -> None:
        help_rows = [
            {"threshold": 0.0, "legit_kept": 1.0, "negatives_abstained": 0.0},
            {"threshold": 1.0, "legit_kept": 1.0, "negatives_abstained": 0.9},
        ]
        cb_rows = [
            {"threshold": 0.0, "legit_kept": 1.0, "negatives_abstained": 0.0},
            {"threshold": 1.0, "legit_kept": 0.90, "negatives_abstained": 1.0},
        ]
        best = mad.best_both_corpora(self._sweeps(help_rows, cb_rows))
        assert best is not None
        # threshold 1.0 breaks the corpus_b bar → only 0.0 remains.
        assert best["threshold"] == 0.0

    def test_no_eligible_returns_none(self) -> None:
        rows = [{"threshold": 0.0, "legit_kept": 0.5, "negatives_abstained": 1.0}]
        assert mad.best_both_corpora(self._sweeps(rows, rows)) is None


class TestC3Verdict:
    def test_useless_best_reports_fails(self) -> None:
        # Legit and negative distributions fully overlap → any threshold
        # holding the legit bar abstains ~nothing → FAILS, not a
        # meaningless "best threshold 0.0".
        same = [_row(5, 1.0, 1.0)] * 20
        stats = {
            "help_legit": same,
            "help_neg": same,
            "cb_legit": same,
            "cb_neg": same,
        }
        text = "\n".join(mad.c3_verdict(stats))
        assert "FAILS" in text
        assert "best threshold: **" not in text

    def test_clean_separation_reports_best(self) -> None:
        legit = [_row(10, 3.0, 5.0)] * 20
        negs = [_row(1, 0.2, 0.1)] * 20
        stats = {"help_legit": legit, "help_neg": negs, "cb_legit": legit, "cb_neg": negs}
        text = "\n".join(mad.c3_verdict(stats))
        assert "best threshold: **" in text
        assert "negatives abstained 100.0%" in text


class TestReportEndToEnd:
    def test_build_report_runs_on_live_fixtures(self) -> None:
        """Full run over the bundled corpus + corpus_b fixtures.

        Pins the section structure, not the numbers.
        """
        report = mad.build_report()
        for section in [
            "## M1 — score distributions",
            "## M1 — bundled-corpus calibration",
            "### R1-strict view (gate set must hold 100%)",
            "## M2 — C3 relative-heuristic sweep",
            "Single-token legit queries",
        ]:
            assert section in report, f"missing section: {section}"
        assert "Recommended bundled `min_score` = **" in report
